// Usage: npm install --prefix /tmp/triptrail-pgcheck @electric-sql/pglite
// PGLITE_MODULE=/tmp/triptrail-pgcheck/node_modules/@electric-sql/pglite/dist/index.js node scripts/test_cloud_schema.mjs
const { PGlite } = await import(process.env.PGLITE_MODULE || '@electric-sql/pglite');
import fs from 'node:fs';
import assert from 'node:assert/strict';
const db = new PGlite();
await db.exec(`create role anon; create role authenticated; create schema storage; create table storage.buckets(id text primary key,name text,public boolean,file_size_limit bigint); create table storage.objects(id uuid,bucket_id text); create table public.triptrail_cloud_records(id uuid); `);
await db.exec(fs.readFileSync(process.cwd()+'/docs/cloud-schema.sql','utf8'));
await db.exec(fs.readFileSync(process.cwd()+'/docs/cloud-backups.sql','utf8'));
await db.exec(fs.readFileSync(process.cwd()+'/docs/cloud-atomic-save.sql','utf8'));
await db.exec(fs.readFileSync(process.cwd()+'/docs/cloud-atomic-save.sql','utf8'));
await db.exec(fs.readFileSync(process.cwd()+'/docs/cloud-recycle.sql','utf8'));
await db.exec(fs.readFileSync(process.cwd()+'/docs/cloud-day-city.sql','utf8'));
await db.exec(fs.readFileSync(process.cwd()+'/docs/cloud-arrangement-types.sql','utf8'));
await db.exec(fs.readFileSync(process.cwd()+'/docs/cloud-day-city.sql','utf8'));
const id=n=>'00000000-0000-4000-8000-'+String(n).padStart(12,'0');
const media={id:id(20),localIdentifier:'',kindRaw:'image',caption:'test',createdAt:1790000000000,sortOrder:0,cloudPath:'test/hash.jpg'};
const voucher={id:'voucher',name:'ticket',mimeType:'text/plain',dataBase64:'aGVsbG8='};
const item={transportRaw:'飞机',attractionTypeRaw:'museum',id:id(3),title:'place',categoryRaw:'景点',startTime:1790000000000,endTime:1790003600000,address:'a',note:'n',playDurationMinutes:60,reservationInfo:'reserved',cost:3.2,isCompleted:false,sortOrder:0,media:[media],vouchers:[voucher]};
const trip={id:id(1),title:'trip',destination:'上海',startDate:1790000000000,endDate:1790003600000,note:'n',createdAt:1790000000000,days:[{id:id(2),date:1790000000000,title:'day',city:'银川',note:'n',sortOrder:0,items:[item]}]};
const story={id:id(4),title:'story',destination:'上海',startDate:1790000000000,endDate:1790003600000,summary:'memory',createdAt:1790000000000,syncScopeRaw:'trip',sourceSelectionIDsRaw:'',coverMedia:media,days:[{id:id(5),date:1790000000000,title:'day',note:'n',details:'detail',didMigrateInlineSummary:true,sortOrder:0}],entries:[{id:id(6),title:'entry',categoryRaw:'景点',timeLabel:'morning',address:'a',note:'n',sortOrder:0,storyDayID:id(5),media:[media]}]};
async function save(kind,payload,rev){
 const rpc = rev ? 'triptrail_patch_record($1,$2,$3,$4::jsonb,$5,$6::jsonb)' : 'triptrail_save_record($1,$2,$3,$4::jsonb,$5)';
 const args=[payload.id,kind,payload.title,JSON.stringify(payload),rev];
 if(rev) args.push(JSON.stringify(payload));
 return (await db.query('select * from public.'+rpc,args)).rows[0];
}
await db.exec('set role anon');
const savedTrip=await save('trip',trip,0);
assert.equal(savedTrip.payload.days[0].city,'银川');
assert.equal(savedTrip.payload.days[0].items[0].transportRaw,'飞机');
assert.equal(savedTrip.payload.days[0].items[0].attractionTypeRaw,'museum');
assert.equal(savedTrip.payload.days[0].items[0].media[0].cloudPath,media.cloudPath);
assert.equal(savedTrip.payload.days[0].items[0].vouchers[0].dataBase64,voucher.dataBase64);
const savedStory=await save('story',story,0);
assert.equal(savedStory.payload.entries[0].storyDayID,id(5));
assert.equal(savedStory.payload.coverMedia.cloudPath,media.cloudPath);
const fav={...item,id:id(7),isFavorite:true};await save('favorite',fav,0);
await assert.rejects(save('trip',trip,0),e=>e.code==='PT409');
const mediaVersion = (await db.query('select xmin::text as version from public.triptrail_trip_item_media where root_id=$1',[trip.id])).rows[0].version;
await save('trip',{...trip,title:'updated'},1);
assert.equal((await db.query('select xmin::text as version from public.triptrail_trip_item_media where root_id=$1',[trip.id])).rows[0].version,mediaVersion,'Title save must not rewrite unrelated media');
await assert.rejects(save('trip',{...trip,title:'stale'},1),e=>e.code==='PT409');
const invalid=structuredClone(trip);invalid.days[0].items[0].media[0].cloudPath=null;
await assert.rejects(save('trip',invalid,2));
assert.equal((await db.query('select title,revision from public.triptrail_trips')).rows[0].title,'updated');
assert.equal((await db.query('select count(*)::int n from public.triptrail_trip_item_media')).rows[0].n,1);
await save('trip',{...trip,days:[]},2);
assert.equal((await db.query('select count(*)::int n from public.triptrail_trip_item_media')).rows[0].n,0);
await db.query('insert into public.triptrail_backups(id,object_path,bytes,sha256,chunk_count) values($1,$2,12,$3,1)',[id(8),id(8)+'.triptrailbackup','a'.repeat(64)]);
assert.equal((await db.query('select ready from public.triptrail_backups')).rows[0].ready,false);
await db.exec("update public.triptrail_backups set ready=true; update public.triptrail_backups set deleting=true; delete from public.triptrail_backups;");
await db.exec('reset role');
assert.equal((await db.query("select count(*)::int n from information_schema.columns where table_schema='public' and table_name like 'triptrail_%' and data_type='jsonb' and table_name<>'triptrail_cloud_records'")).rows[0].n,0);
await db.exec(fs.readFileSync(process.cwd()+'/docs/cloud-recycle.sql','utf8'));
await db.exec('set role anon');
for (const [kind,payload] of [['trip',trip],['story',story],['favorite',fav]]) {
 const before=(await db.query('select revision from public.triptrail_cloud_records where id=$1',[payload.id])).rows[0].revision;
 await db.query('select public.triptrail_trash_record($1,$2)',[payload.id,kind]);
 const expiry=(await db.query('select expires_at_ms from public.triptrail_deleted_records where id=$1',[payload.id])).rows[0].expires_at_ms;
 await db.query('select public.triptrail_trash_record($1,$2)',[payload.id,kind]);
 assert.equal((await db.query('select expires_at_ms from public.triptrail_deleted_records where id=$1',[payload.id])).rows[0].expires_at_ms,expiry);
 assert.equal((await db.query('select * from public.triptrail_cloud_records where id=$1',[payload.id])).rows.length,0);
 await assert.rejects(save(kind,payload,before),e=>e.code==='PT410');
 await db.query('select public.triptrail_restore_record($1,$2)',[payload.id,kind]);
 assert.equal(Number((await db.query('select revision from public.triptrail_cloud_records where id=$1',[payload.id])).rows[0].revision),Number(before)+1);
 await assert.rejects(save(kind,payload,before),e=>e.code==='PT409');
 await db.query('select public.triptrail_trash_record($1,$2)',[payload.id,kind]);
 await db.query('update public.triptrail_deleted_records set expires_at_ms=0 where id=$1',[payload.id]);
 await assert.rejects(db.query('select public.triptrail_restore_record($1,$2)',[payload.id,kind]),e=>e.code==='PT410');
 await db.query('select public.triptrail_purge_recycle()');
 await assert.rejects(save(kind,payload,0),e=>e.code==='PT410');
}
const retryTrip={...trip,id:id(100)};
await save('trip',retryTrip,0);
await db.query('select public.triptrail_trash_record($1,$2,$3)',[retryTrip.id,'trip',id(101)]);
await db.query('select public.triptrail_restore_record($1,$2)',[retryTrip.id,'trip']);
await db.query('select public.triptrail_trash_record($1,$2,$3)',[retryTrip.id,'trip',id(101)]);
assert.equal((await db.query('select * from public.triptrail_cloud_records where id=$1',[retryTrip.id])).rows.length,1,'Retry of acknowledged delete after restore must not delete twice');
assert.equal((await db.query('select count(*)::int n from public.triptrail_stories')).rows[0].n,0);
assert.equal((await db.query('select count(*)::int n from public.triptrail_story_entry_media')).rows[0].n,0);
await db.exec('reset role');
await db.exec(fs.readFileSync(process.cwd()+'/docs/cloud-recycle.sql','utf8'));
console.log('PASS: recycle all three kinds, idempotent deletion, hidden active rows, stale writes blocked, restore revision, expiry, cascading purge, persistent tombstones, repeatable migration.');
console.log('PASS: relational trip/story/favorite roundtrip, media/vouchers, anon RLS, stale revision, rollback, cascade cleanup, backup staging/delete; no persisted JSONB.');
await db.close();
