import fs from 'node:fs';
import assert from 'node:assert/strict';
const { PGlite } = await import(process.env.PGLITE_MODULE || '@electric-sql/pglite');
const db = new PGlite();
await db.exec(`create role anon; create role authenticated; create schema storage;
create table storage.buckets(id text primary key,name text,public boolean,file_size_limit bigint);
create table storage.objects(id uuid,bucket_id text,name text,created_at timestamptz default now(),updated_at timestamptz default now());
grant usage on schema storage to anon,authenticated; grant select on storage.objects to anon,authenticated;`);
for (const file of ['cloud-schema.sql','cloud-backups.sql','cloud-recycle.sql','cloud-cleanup.sql','cloud-cleanup.sql']) await db.exec(fs.readFileSync('docs/'+file,'utf8'));
const id='00000000-0000-4000-8000-000000000001';
await db.exec(`insert into public.triptrail_stories(id,title,destination,"startDate","endDate",summary,"createdAt","syncScopeRaw","sourceSelectionIDsRaw") values('${id}','test','city',0,0,'',0,'trip','');`);
const cover = async path => db.query(`insert into public.triptrail_story_cover_media(root_id,id,"localIdentifier","kindRaw",caption,"createdAt","sortOrder","cloudPath") values($1,$1,'','image','',0,0,$2)`,[id,path]);
await cover('used.jpg');
await db.exec(`insert into storage.objects(bucket_id,name,created_at,updated_at) select 'triptrail-media',p,now()-interval '10 days',now()-interval '10 days' from unnest(array['used.jpg','orphan.jpg','rescued.jpg']) p;
insert into storage.objects(bucket_id,name) values('triptrail-media','new.jpg');
insert into public.triptrail_backups(id,object_path,bytes,chunk_count,sha256) values('${id}','${id}.triptrailbackup',1,1,repeat('a',64));
insert into storage.objects(bucket_id,name,created_at,updated_at) values('triptrail-backups','${id}.triptrailbackup/0',now()-interval '10 days',now()-interval '10 days'),('triptrail-backups','orphan-backup/0',now()-interval '10 days',now()-interval '10 days');
set role anon;`);
const preview=async()=> (await db.query('select * from public.triptrail_cleanup_candidates()')).rows;
assert.equal((await preview()).length,0,'first discovery never deletes');
await db.exec(`update public.triptrail_gc_objects set first_seen=now()-interval '2 days';`);
const files=await preview();assert.equal(files.length,3);
assert.equal((await db.query('select * from public.triptrail_gc_objects where deleting')).rows.length,0,'preview/cancel never claims');
await cover('rescued.jpg');
const claim=async()=> (await db.query('select * from public.triptrail_cleanup_claim($1::jsonb)',[JSON.stringify(files)])).rows;
const claimed=await claim();assert.equal(claimed.length,2,'reference created after preview protected');
await assert.rejects(cover('orphan.jpg'),/TRIPTRAIL_MEDIA_RETIRED/);
assert.equal((await claim()).length,2,'failed Storage deletion retryable');
assert.equal((await db.query("select public.triptrail_media_available('orphan.jpg') as available")).rows[0].available,false);
assert.equal((await db.query("select public.triptrail_media_available('used.jpg') as available")).rows[0].available,true);
await db.exec(`reset role; delete from storage.objects where name in ('orphan.jpg','orphan-backup/0'); set role anon;`);
assert.equal((await preview()).length,0,'deleted objects not offered again');
await db.query('select public.triptrail_trash_record($1,$2,$3)',[id,'story','00000000-0000-4000-8000-000000000002']);
assert.equal((await preview()).length,0,'recycle media remains protected');
console.log('PASS: repeatable migration, grace period, preview cancellation, shared/cover/recycle references, incomplete backup protection, confirmation recheck, retired-path guard, retry, availability.');
await db.close();
