const { PGlite } = await import(process.env.PGLITE_MODULE || '@electric-sql/pglite');
import fs from 'node:fs';
import assert from 'node:assert/strict';
const db = new PGlite();
await db.exec(`create role anon; create role authenticated; create schema storage; create table storage.buckets(id text primary key,name text,public boolean,file_size_limit bigint); create table storage.objects(id uuid,bucket_id text); create table public.triptrail_cloud_records(id uuid);`);
for (const name of ['cloud-schema.sql','cloud-backups.sql','cloud-recycle.sql','cloud-day-city.sql','cloud-arrangement-types.sql','cloud-atomic-save.sql']) await db.exec(fs.readFileSync('docs/'+name,'utf8'));
const id = n => '00000000-0000-4000-8000-'+String(n).padStart(12,'0');
const media = {id:id(20),localIdentifier:'',kindRaw:'image',caption:'photo',createdAt:1790000000000,sortOrder:0,cloudPath:'test/memory.jpg'};
const item = {id:id(3),title:'actual itinerary',categoryRaw:'景点',startTime:1790000000000,endTime:1790003600000,address:'',note:'plan',playDurationMinutes:60,reservationInfo:'',cost:0,isCompleted:false,isFavorite:false,favoriteCity:'',favoriteCreatedAt:1790000000000,sortOrder:0,media:[],vouchers:[]};
const trip = {id:id(1),title:'trip',destination:'银川',licensePlate:'',startDate:1790000000000,endDate:1790003600000,note:'plan',createdAt:1790000000000,days:[{id:id(2),date:1790000000000,title:'day',note:'plan day',city:'银川',sortOrder:0,items:[item]}]};
const story = {id:id(4),sourceTripID:trip.id,title:'legacy footprint title',destination:'宁夏',startDate:trip.startDate,endDate:trip.endDate,summary:'memory summary',createdAt:trip.createdAt,syncScopeRaw:'trip',sourceSelectionIDsRaw:'',coverMedia:{...media,id:id(21),cloudPath:'test/cover.jpg'},coverZoom:1.5,days:[{id:id(5),sourceDayID:id(2),date:trip.startDate,title:'legacy day',note:'memory day',details:'journal',didMigrateInlineSummary:true,sortOrder:0}],entries:[{id:id(6),sourceItemID:id(3),title:'legacy title',categoryRaw:'景点',timeLabel:'',address:'',note:'remember this',sortOrder:0,storyDayID:id(5),media:[media]}]};
async function save(kind,p,rev=0) {return (await db.query('select * from public.triptrail_save_record($1,$2,$3,$4::jsonb,$5)',[p.id,kind,p.title,JSON.stringify(p),rev])).rows[0];}
await save('trip',trip); await save('story',story);
const independent={...story,id:id(30),sourceTripID:null,days:[{...story.days[0],id:id(31),sourceDayID:null}],entries:[{...story.entries[0],id:id(32),sourceItemID:null,storyDayID:id(31),media:[]}]};
await save('story',independent);
const orphan={...independent,id:id(40),days:[],entries:[{...independent.entries[0],id:id(42),storyDayID:null,note:'orphan memory'}]};
await save('story',orphan);
const sql=fs.readFileSync('docs/cloud-unified-journeys.sql','utf8');
await db.exec(sql);
const row=async key=>(await db.query('select * from public.triptrail_cloud_records where id=$1',[key])).rows[0];
let migrated=await row(trip.id);
assert.equal(migrated.payload.days[0].items[0].title,'actual itinerary');
assert.equal(migrated.payload.days[0].items[0].note,'plan');
assert.equal(migrated.payload.days[0].items[0].journalNote,'remember this');
assert.equal(migrated.payload.days[0].journalNote,'memory day');
assert.equal(migrated.payload.coverMedia.cloudPath,'test/cover.jpg');
assert.equal(migrated.payload.coverZoom,1.5);
assert.equal(migrated.payload.days[0].items[0].media[0].cloudPath,media.cloudPath);
assert.equal((await row(independent.id)).kind,'trip');
assert.equal((await row(orphan.id)).payload.days.flatMap(d=>d.items)[0].journalNote,'orphan memory');
assert.equal((await db.query("select count(*)::int n from public.triptrail_cloud_records where kind='story'")).rows[0].n,0);
assert.equal((await db.query('select count(*)::int n from public.triptrail_unified_migration_backup')).rows[0].n,4);
await db.exec(sql); assert.deepEqual(await row(trip.id),migrated,'Migration must not merge twice or change revision on retry');
await db.exec('set role anon');
const patch=async(p,rev)=>(await db.query('select * from public.triptrail_patch_record($1,$2,$3,$4::jsonb,$5,null)',[p.id,'trip',p.title,JSON.stringify(p),rev])).rows[0];
const xmin=(await db.query('select xmin::text v from public.triptrail_trip_item_media where root_id=$1',[trip.id])).rows[0].v;
const changed=structuredClone(migrated.payload);changed.days[0].items[0].journalNote='new memory';
const saved=await patch(changed,migrated.revision);
assert.equal(saved.payload.days[0].items[0].journalNote,'new memory');
assert.equal((await db.query('select xmin::text v from public.triptrail_trip_item_media where root_id=$1',[trip.id])).rows[0].v,xmin);
await assert.rejects(patch(changed,migrated.revision),e=>e.code==='PT409');
await assert.rejects(save('trip',trip,saved.revision),e=>e.code==='PT426');
await assert.rejects(patch(trip,saved.revision),e=>e.code==='PT426');
const invalid=structuredClone(changed);invalid.days[0].items[0].media[0].cloudPath=null;
await assert.rejects(patch(invalid,saved.revision));
assert.equal(Number((await row(trip.id)).revision),Number(saved.revision));
assert.equal((await db.query("select public.triptrail_media_referenced('test/cover.jpg') as v")).rows[0].v,true);
console.log('PASS: unified migration preserves itinerary, journal, media, cover; standalone stories; idempotency; backups; anon CAS; rollback; unchanged media; legacy writes rejected.');
await db.close();
