import fs from 'node:fs';
import assert from 'node:assert/strict';
const { PGlite } = await import(process.env.PGLITE_MODULE || '@electric-sql/pglite');
const db = new PGlite();
await db.exec(`create role anon; create role authenticated; create schema storage;
create table storage.objects(bucket_id text default 'triptrail-media', metadata jsonb);
grant usage on schema storage to anon, authenticated;
grant select on storage.objects to anon, authenticated;
alter table storage.objects enable row level security;
create policy app_read on storage.objects for select to anon, authenticated using (bucket_id in ('triptrail-media', 'triptrail-backups'));
insert into storage.objects(metadata) values ('{"size":1024}'), ('{"size":"2048"}'), ('{}');`);
await db.exec(fs.readFileSync('docs/cloud-storage-usage.sql', 'utf8'));
await db.exec('set role anon');
const get = async () => (await db.query('select * from public.triptrail_storage_usage()')).rows[0];
const first = await get();
assert.equal(Number(first.object_bytes), 3072);
assert.ok(Number(first.database_bytes) > 0);
await db.exec(`reset role; insert into storage.objects(bucket_id,metadata) values ('private-other-app','{"size":9999}'); set role anon`);
assert.equal(Number((await get()).object_bytes), 3072, 'Unrelated buckets must not be counted');
await assert.rejects(db.query("insert into storage.objects(metadata) values ('{}')"));
const attributes = await db.query("select prosecdef from pg_proc where proname = 'triptrail_storage_usage'");
assert.equal(attributes.rows[0].prosecdef, false);
console.log('PASS: invoker-only RPC, database bytes, media/backup aggregation, bucket RLS and read-only access');
await db.close();
